from unittest.mock import patch, MagicMock
import pytest

from touchque.config import Config
from touchque.http_client import HttpClient
from touchque.exceptions import TouchQueAPIException, TouchQueNetworkException


def make_client(**overrides):
    config = Config(api_key="tq_auth_test123", api_secret="shh", **overrides)
    return HttpClient(config)


def fake_response(status_code=200, json_data=None):
    resp = MagicMock()
    resp.status_code = status_code
    resp.json.return_value = json_data or {}
    return resp


@patch("touchque.http_client.requests.post")
def test_post_attaches_signed_headers(mock_post):
    mock_post.return_value = fake_response(200, {"ok": True})
    client = make_client()

    result = client.post("/auth/generate-secret", {"externalUsername": "a@b.com"})

    assert result == {"ok": True}
    _, kwargs = mock_post.call_args
    headers = kwargs["headers"]
    assert headers["x-api-key"] == "tq_auth_test123"
    assert len(headers["x-signature"]) == 64  # hex sha256
    assert "x-timestamp" in headers
    assert "x-nonce" in headers


@patch("touchque.http_client.requests.post")
def test_post_two_calls_produce_different_nonces(mock_post):
    mock_post.return_value = fake_response(200, {"ok": True})
    client = make_client()

    client.post("/login/request", {"a": 1})
    client.post("/login/request", {"a": 1})

    nonce1 = mock_post.call_args_list[0].kwargs["headers"]["x-nonce"]
    nonce2 = mock_post.call_args_list[1].kwargs["headers"]["x-nonce"]
    assert nonce1 != nonce2


@patch("touchque.http_client.requests.get")
def test_get_signs_an_empty_body_request(mock_get):
    mock_get.return_value = fake_response(200, {"status": "PENDING"})
    client = make_client()

    result = client.get("/login/status/req_1")

    assert result == {"status": "PENDING"}
    assert len(mock_get.call_args.kwargs["headers"]["x-signature"]) == 64


@patch("touchque.http_client.requests.post")
def test_post_raises_touchque_api_exception_on_4xx(mock_post):
    # NOTE: unlike the Node SDK (which prefers `message` over `error`), this
    # Python client's real implementation (http_client.py) prefers the
    # `error` field over `message` — a genuine, pre-existing cross-language
    # inconsistency (flagged, not fixed here; out of this phase's scope).
    mock_post.return_value = fake_response(401, {"error": "unauthorized", "message": "Invalid API key"})
    client = make_client()

    with pytest.raises(TouchQueAPIException) as exc_info:
        client.post("/auth/generate-secret", {})

    assert "unauthorized" in str(exc_info.value)


@patch("touchque.http_client.requests.post", side_effect=__import__("requests").exceptions.ConnectionError("boom"))
def test_post_wraps_network_errors(mock_post):
    client = make_client()
    with pytest.raises(TouchQueNetworkException, match="Network Error"):
        client.post("/auth/generate-secret", {})


# ── Cross-language SDK contract fixtures (sdks/fixtures/signature-vectors.json) ──
# Generated by the backend from utils/canonicalSignature.js. Asserted here and in
# the node/go/php suites so every SDK signs identically to the server.
import json
import os

_FIXTURE_PATH = os.path.join(
    os.path.dirname(__file__), "..", "fixtures", "signature-vectors.json"
)
with open(_FIXTURE_PATH) as _f:
    _SIG_FIXTURE = json.load(_f)


@pytest.mark.parametrize("vec", _SIG_FIXTURE["vectors"], ids=lambda v: v["description"])
def test_signature_matches_backend_vector(vec):
    client = HttpClient(Config(api_key="tq_x", api_secret=_SIG_FIXTURE["secret"]))
    actual = client._sign_request(
        vec["method"], vec["signed_path"], vec["body"], vec["timestamp"], vec["nonce"]
    )
    assert actual == vec["expected_signature"]
